import Parser from "rss-parser";
const parser = new Parser({ headers: { "User-Agent": "Mozilla/5.0 RSS-Content-Engine" }, timeout: 10000 });
const FEEDS = [{ url: "https://feeds.feedburner.com/TheHackersNews", name: "The Hacker News" },{ url: "https://hnrss.org/frontpage", name: "Hacker News Front Page" },{ url: "https://www.infoq.com/feed/", name: "InfoQ" },{ url: "https://changelog.com/feed", name: "Changelog" },{ url: "https://css-tricks.com/feed/", name: "CSS-Tricks" }];
function humanize(text){ try{ let t = String(text||"").replace(/[—–]/g,". ").replace(/;/g,",").replace(/\s+/g," ").trim(); t = t.split(".").map(s=>s.trim()).filter(Boolean).slice(0,8).join(". ")+"."; return t; }catch{return "";} }
function viralityScore(text){ try{ let score=50; if(text.split(".")[0]?.length>10) score+=10; if(/\d+%|\d+\/\d+|CVE-|\\$/.test(text)) score+=10; if(/(not|never|always|wrong|myth|secret)/i.test(text)) score+=10; if(/[?!]/.test(text)) score+=5; return Math.max(0,Math.min(100,score)); }catch{return 50;} }
function platformMax(p){ const limits={x:280,bluesky:300,reddit:4000,facebook:63206,linkedin:3000,medium:3000,substack:3000,devto:3000}; return limits[p]||3000; }
function tailor(text, platform){ try{ const base=humanize(text); const max=platformMax(platform); if(platform==="x"||platform==="bluesky"){ const words=base.split(" "); let out=""; for(let i=0;i<words.length&&out.length<max;i++){ if(out.length+words[i].length+1>max) break; out+= (out?" ":"")+words[i]; } return out; } return base.slice(0,max); }catch{return "";} }
function hashtagsFor(platform){ const map={ x:["#TechNews","#CyberSecurity","#DevOps"], linkedin:["#Technology","#Leadership","#Innovation"], reddit:["r/technology","r/devops"], facebook:["#Tech","#Security"], medium:["#Technology","#Programming"], substack:["#TechNewsletter"], devto:["#webdev","#programming"], bluesky:["#tech","#news"] }; return (map[platform]||[]).join(" "); }
function utmLink(url){ try{ const u=new URL(url); u.searchParams.set("utm_source","rss"); u.searchParams.set("utm_medium","social"); u.searchParams.set("utm_campaign","digest"); return u.toString(); }catch{return url;} }
function imageUrl(title){ const txt=encodeURIComponent((title||"").slice(0,60)); return `https://via.placeholder.com/1200x630.png?text=${txt}`; }
async function fetchFeeds(){ const articles=[]; const seen=new Set(); for(const f of FEEDS){ try{ const feed=await parser.parseURL(f.url); for(const item of feed.items.slice(0,5)){ if(!item.link||seen.has(item.link)) continue; seen.add(item.link); articles.push({ title:item.title||"", url:item.link, source:f.name, excerpt:item.contentSnippet||item.content||"" }); } }catch(e){} } return articles; }
async function synthesizeForPlatform(article, platform){ try{ const key=process.env.GROQ_API_KEY; if(!key) return humanize(article.excerpt); const styleMap={ x:"Punchy 1-sentence hook with 1 emoji, max 280 chars.", bluesky:"Concise 2-sentence take, max 300 chars.", reddit:"Detailed summary with context.", linkedin:"Professional post with hook and value.", facebook:"Conversational post with hook.", medium:"Short article intro paragraph.", substack:"Newsletter-style summary.", devto:"Developer-focused summary." }; const system=`Write in active voice, short sentences, no em dashes, no semicolons. ${styleMap[platform]}`; const prompt=`Summarize this article for ${platform}: ${article.title} ${article.excerpt.slice(0,400)}`; const resp=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.1-70b-versatile",messages:[{role:"system",content:system},{role:"user",content:prompt}],temperature:0.3})}); const data=await resp.json(); return data.choices?.[0]?.message?.content||humanize(article.excerpt); }catch{ return humanize(article.excerpt); } }
export default async function handler(req,res){ const allowed=req.headers["x-vercel-cron"]==="1"||req.query.test==="1"; if(!allowed) return res.status(401).send("Unauthorized"); try{ const articles=await fetchFeeds(); const platforms=["x","facebook","reddit","linkedin","medium","substack","devto","bluesky"]; const results=[]; for(const a of articles.slice(0,10)){ const row={ date:new Date().toISOString().slice(0,10), title:a.title, url:a.url, source:a.source, image_url:imageUrl(a.title), alt_text:`Summary card for ${a.title}`, utm_link:utmLink(a.url), scores:{}}; let allPass=true; for(const p of platforms){ const raw=await synthesizeForPlatform(a,p); const tailored=tailor(raw,p); const score=viralityScore(tailored); row[p]=tailored; row[`${p}_hashtags`]=hashtagsFor(p); row.scores[p]=score; if(score<=75) allPass=false; } if(allPass){ results.push(row); } } if(process.env.GOOGLE_SHEETS_WEBHOOK_URL&&results.length){ await fetch(process.env.GOOGLE_SHEETS_WEBHOOK_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(results)}).catch(()=>{}); } res.status(200).json({ ok:true, count:results.length, articlesFetched:articles.length, sample:results[0]||null }); }catch(e){ res.status(500).json({ error:e.message }); } }

