import Parser from "rss-parser";
const parser = new Parser();
const FEEDS = [{ url: "https://feeds.feedburner.com/TheHackersNews", name: "The Hacker News" },{ url: "https://hnrss.org/frontpage", name: "Hacker News Front Page" },{ url: "https://www.infoq.com/feed/", name: "InfoQ" },{ url: "https://changelog.com/feed", name: "Changelog" },{ url: "https://css-tricks.com/feed/", name: "CSS-Tricks" }];
function humanize(text){ let t = text.replace(/[—–]/g,". ").replace(/;/g,",").replace(/\s+/g," ").trim(); t = t.split(".").map(s=>s.trim()).filter(Boolean).slice(0,8).join(". ") + "."; return t; }
function tailor(text, platform){ const base = humanize(text); const limits = { x:280, bluesky:300, reddit:4000, facebook:63206, linkedin:3000, medium:3000, substack:3000, devto:3000 }; const max = limits[platform]||3000; if(platform==="x"||platform==="bluesky"){ const words = base.split(" "); let out=""; for(let i=0;i<words.length&&out.length<max;i++){ if(out.length+words[i].length+1>max) break; out+= (out?" ":"")+words[i]; } return out; } if(platform==="reddit"){ return base.slice(0,4000); } return base.slice(0,max); }
async function fetchFeeds(){ const articles=[]; for(const f of FEEDS){ try{ const feed = await parser.parseURL(f.url); for(const item of feed.items.slice(0,5)){ articles.push({ title:item.title, url:item.link, source:f.name, excerpt:item.contentSnippet||"" }); } }catch(e){} } return articles; }
async function synthesize(article){ const key=process.env.GROQ_API_KEY; if(!key) return humanize(article.excerpt); const prompt=`Summarize this article in 3 short active sentences, preserve facts: ${article.title} ${article.excerpt.slice(0,400)}`; const resp=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.1-70b-versatile",messages:[{role:"system",content:"Write in active voice, short sentences, no em dashes, no semicolons."},{role:"user",content:prompt}],temperature:0.3})}); const data=await resp.json(); return data.choices?.[0]?.message?.content||article.excerpt;
}
async function createGitHubIssue(owner,repo,token,title,body){ await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`,{method:"POST",headers:{Authorization:`token ${token}`,"Content-Type":"application/json","User-Agent":"RSS-Content-Engine"},body:JSON.stringify({title,body})});}
export default async function handler(req,res){ const allowed=req.headers["x-vercel-cron"]==="1"||req.query.test==="1"; if(!allowed) return res.status(401).send("Unauthorized"); try{ const articles=await fetchFeeds(); const results=[]; const platforms=["x","facebook","reddit","linkedin","medium","substack","devto","bluesky"]; for(const a of articles.slice(0,4)){ const summary=await synthesize(a); const row={ date:new Date().toISOString().slice(0,10), title:a.title, url:a.url, source:a.source }; platforms.forEach(p=>row[p]=tailor(summary,p)); results.push(row); } const issueBody=`# HITL Review ${new Date().toISOString().slice(0,10)}\n\nGenerated ${results.length} posts.`; if(process.env.GITHUB_TOKEN){ await createGitHubIssue("Agentcycoza","RSS-CONTENT-ENGINE",process.env.GITHUB_TOKEN,`HITL Review ${new Date().toISOString().slice(0,10)}`,issueBody); } if(process.env.GOOGLE_SHEETS_WEBHOOK_URL){ await fetch(process.env.GOOGLE_SHEETS_WEBHOOK_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(results)}); } res.status(200).json({ ok:true, count:results.length, sample:results[0] }); }catch(e){ res.status(500).json({ error:e.message }); } }

