import Parser from "rss-parser";
const parser = new Parser();
const FEEDS = [{ url: "https://feeds.feedburner.com/TheHackersNews", name: "The Hacker News" },{ url: "https://hnrss.org/frontpage", name: "Hacker News Front Page" },{ url: "https://www.infoq.com/feed/", name: "InfoQ" },{ url: "https://changelog.com/feed", name: "Changelog" },{ url: "https://css-tricks.com/feed/", name: "CSS-Tricks" }];
function humanize(text){ let t = text.replace(/[—–]/g,". ").replace(/;/g,",").replace(/\s+/g," ").trim(); t = t.split(".").map(s=>s.trim()).filter(Boolean).slice(0,6).join(". ") + "."; return t; }
function tailorForPlatform(text, platform){ const clean = humanize(text); if(platform==="x"){ const words = clean.split(" "); const chunks = []; for(let i=0;i<words.length;i+=20){ chunks.push(words.slice(i,i+20).join(" ")); } return chunks.slice(0,5).join("\n\n"); } if(platform==="linkedin"){ return clean.slice(0,1500); } if(platform==="substack"){ return clean; } return clean; }
async function fetchFeeds(){ const articles=[]; for(const f of FEEDS){ try{ const feed = await parser.parseURL(f.url); for(const item of feed.items.slice(0,5)){ articles.push({ title:item.title, url:item.link, source:f.name, excerpt:item.contentSnippet||"" }); } }catch(e){ console.warn("Feed error",f.name,e.message); } } return articles; }
async function synthesize(article){ const key=process.env.GROQ_API_KEY; if(!key) return humanize(article.excerpt); const prompt=`Summarize this article in 3 short active sentences, preserve facts: ${article.title} ${article.excerpt.slice(0,400)}`; const resp=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.1-70b-versatile",messages:[{role:"system",content:"Write in active voice, short sentences, no em dashes, no semicolons."},{role:"user",content:prompt}],temperature:0.3})}); const data=await resp.json(); return data.choices?.[0]?.message?.content||article.excerpt;
}
async function createGitHubIssue(owner,repo,token,title,body){ await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`,{method:"POST",headers:{Authorization:`token ${token}`,"Content-Type":"application/json","User-Agent":"RSS-Content-Engine"},body:JSON.stringify({title,body})});}
export default async function handler(req,res){ const allowed=req.headers["x-vercel-cron"]==="1"||req.query.test==="1"; if(!allowed) return res.status(401).send("Unauthorized"); try{ const articles=await fetchFeeds(); const results=[]; for(const a of articles.slice(0,4)){ const summary=await synthesize(a); results.push({ title:a.title, url:a.url, source:a.source, linkedin:tailorForPlatform(summary,"linkedin"), x:tailorForPlatform(summary,"x"), substack:tailorForPlatform(summary,"substack") }); } const issueBody=`# HITL Review ${new Date().toISOString().slice(0,10)}\n\nGenerated ${results.length} posts per platform.\n\n${JSON.stringify(results,null,2)}`; const token=process.env.GITHUB_TOKEN; if(token){ await createGitHubIssue("Agentcycoza","RSS-CONTENT-ENGINE",token,`HITL Review ${new Date().toISOString().slice(0,10)}`,issueBody); } res.status(200).json({ ok:true, count:results.length, sample:results[0] }); }catch(e){ res.status(500).json({ error:e.message }); } }

